default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: ishana_interio

test:
  <<: *default
  database: ishana_interio_test

production:
  <<: *default
  url: <%= ENV["DB_URL"] %>